version: '3'

services:
        database:
                image: mysql:5.7
                volumes:
                        - mysql_str:/var/lib/mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: rootpass
                        MYSQL_USER: samiksha
                        MYSQL_PASSWORD: redhat
                        MYSQL_DATABASE: db
           
        adminergui:
                image: adminer:latest
                restart: always
                depends_on:
                        - databse
                ports:
                        - 8080:8080
                environment:
                        ADMINER_DESIGN: nette


